### PR TITLE
Bootcamp 6

### PR DESCRIPTION
**Pull request by thchia**
- Main change is moving from Sequelize to ObjectionJS/Knex.
- Includes single migration for a "users" table.
- Includes seed for single entry in said table.

### CODE REVIEW

**Review by pkamath2 — APPROVED** [review]

**Comment by pkamath2** [comment]
This looks good @thchia. 

Hey @miccheng Are the previous bootcamp participants still using the backend starter kit? Or can we merge our changes to master?

**Comment by thchia** [comment]
@pkamath2 I checked with Michael offline before - fine to merge in as I have tagged the latest commit on master in case anyone needs to go back there.

**Review by miccheng — APPROVED** [review]

**Comment by miccheng** [comment]
LGTM! Merge it!

**Comment by miccheng** [comment]
Should let new tech lead do merge going forward.

**Pull request merged**
